-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 20:59:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plantinha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plantinha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plantinha` DEFAULT CHARACTER SET utf8 ;
USE `plantinha` ;

-- -----------------------------------------------------
-- Table `plantinha`.`painel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantinha`.`painel` (
  `idpainel` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `descricao` TEXT NULL,
  `dia` DATETIME NULL,
  `hash` VARCHAR(200) NULL,
  `key` VARCHAR(200) NULL,
  PRIMARY KEY (`idpainel`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `plantinha`.`tipo_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantinha`.`tipo_acao` (
  `idtipo_acao` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  PRIMARY KEY (`idtipo_acao`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `plantinha`.`acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantinha`.`acao` (
  `idacao` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `dia` DATETIME NULL,
  `idtipo_acao` BIGINT(8) NOT NULL,
  `comando` VARCHAR(200) NULL,
  `idpainel` BIGINT(8) NOT NULL,
  PRIMARY KEY (`idacao`),
  INDEX `fk_acao_tipo_acao_idx` (`idtipo_acao` ASC) VISIBLE,
  INDEX `fk_acao_painel1_idx` (`idpainel` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `plantinha`.`tipo_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantinha`.`tipo_status` (
  `idtipo_status` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  PRIMARY KEY (`idtipo_status`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `plantinha`.`dados_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantinha`.`dados_status` (
  `iddados_status` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `dia` DATETIME NULL,
  `idtipo_status` BIGINT(8) NOT NULL,
  `valor` VARCHAR(10) NULL,
  `idpainel` BIGINT(8) NOT NULL,
  PRIMARY KEY (`iddados_status`),
  INDEX `fk_dados_status_tipo_status1_idx` (`idtipo_status` ASC) VISIBLE,
  INDEX `fk_dados_status_painel1_idx` (`idpainel` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

